# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ed162063f90071bf502d6d9d8f1f3cc31dc5b7648d676f4a7b44cf9b810d756c25896550270bdb2d95c71d47b7dce55743cca1923a32484b7f8c7ac75fad35d

test:
  secret_key_base: 5322323c52ad2bb93aff444f6a4b9e38ad8d8962ea330dee31bf8229808123800cbe0da1397efe30945c50ea5aadd1b5dbed2117d486297cc5b0dd8413bbe086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
